sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mUjZ4hVprZ2EKyH5dzKqlbrRADfTHK7xUWVZYhPn6IY5vkfrlU0lmlDNHX+Qf+POWIfyrqXnD+sJvppZuHmCmiUlDtr22TkRxynxZ7XDFydw7bFWe3ewo885JKarAJBHveiUx3/xqcjfyj7DXmho6N2OzJW4DDIN5WE5YiNrAQrIYs8Vr9ig3Wu7iwAVo0VgFX/g8tBNlcfB7X8lqIOHHQIcDx7j7mTe7/yatgIPSaQ7AUq4q11VzqrAYkKvGIywsH1oh11nP9uvrnOs8bgPGb5taxa6NLB37ANgqA/JwNlTIx0ItMfhcCYbH/e0xv//0blgV8NVTllXgIBe7Ia23RUnVORbslistJZztGdxVSbuTokCQsIf4oWg4JfSwdrOaigU45nCi0pbHgr6vUe+ydweaJ47BhJdRtjz5H+HB+2Ki3IXhE0F0MFJjN/ylyzJ+2U5C000unFWxE2Ee1OimoVdoscyB9y0A50o/yKfRZSk5O0D/dl/55AtSiPR47Ac7eAZG436IbPoKqBjVkfHNqVir+RQB3G+oG1sD7VqzsLWLG+RrBoW6M8VmSoEzZJ6ZvLn3x19LL/KYx2cbTTBEmTglC1qmIepO/Ma89lgA8rijJeOknk2XeF8+4Jl96YlbrJ5sTS1YXYW5dM9+UqHDmydnaHG/kUQ4qF4NbgoN5c=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Confessions-of-an-Inquiring-Spirit-and-Some-Miscellaneous-Pieces_2575
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy